### ISSUE TITLE
Add TRIE Data Structure

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#134] opened 2020-06-27 04:18 UTC
**Algorithm:** 

[TRIE Data Structure](https://en.wikipedia.org/wiki/Trie)

**DS:** 

Trees

**Languages Supported:**

- C
- C++ [ Assigned to @16priyesh ]
- C#
- Java [ Assigned to @16priyesh ]
- Javascript
- Python [ Assigned to @16priyesh ]

**Comment by 16priyesh** [comment] 2020-06-27 05:11
I have coded lots of tries in c++. So, I can write code for trie data structure in c++. I maybe able to convert it to java and python as well since I have a little experience with these languages.

**Comment by HarshCasper** [comment] 2020-06-27 05:13
I have assigned you the Issues in C++, Java and Python @16priyesh 

You can start working on it. Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by 16priyesh** [comment] 2020-06-28 16:03
remote: Permission to TesseractCoding/NeoAlgo.git denied to 16priyesh.
fatal: unable to access 'https://github.com/TesseractCoding/NeoAlgo.git/': The requested URL returned error: 403

I'm haven't been able to sort it out since yesterday. I followed the What is Pull Request and how to do it guide on the README of this repo.
Sorry for the delay caused by me.

**Comment by HarshCasper** [comment] 2020-06-29 03:23
Hello, @16priyesh 

Can you please let us know what was the Issue. Probably you tried to push directly to the Master which caused the error. We are here to help you sort this out and make your Contribution smooth.

**Comment by suraj0223** [comment] 2020-08-07 10:02
Hello @HarshCasper wanna to work on this issue in C++. Is anyone working on that.

**Comment by atarax665** [comment] 2020-10-04 06:01
Closing by #1278

**Closed as completed by atarax665** 2020-10-04 06:01 UTC
Labels: enhancement, good first issue, C, JavaScript, hard, C-Sharp
