### ISSUE TITLE
Removing Zero Sum Consecutive from Linked List.

### ISSUE THREAD

**Issue by Striver08** [HarshCasper/NeoAlgo#2919] opened 2021-03-12 19:59 UTC
## 💥 Proposal
I am a GSSOC'21 participant  and I would like to implement the algo to remove zero sum consecutive from Linked List in Python.

**Comment by bhav09** [comment] 2021-03-13 01:23
Hey @Striver08,
You need to add some description of the problem statement.  Only then we would be able to assign it to you :)

**Comment by HitainKakkar** [comment] 2021-03-14 17:16
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by OnewayShruti** [comment] 2021-03-15 12:07
Hey @bhav09 
I am a GSSOC'21 participant(Discord Username -Oneway_Shruti(P)#9537)
I wish to contribute to Removing Zero Sum Consecutive from Linked List which states that  I can write the code in python which states that we have to repeatedly delete consecutive sequences of nodes that sum to 0 until there are no such sequences
Do consider assigning me on this.

**Comment by bhav09** [comment] 2021-03-15 14:37
Go for it Shruti.

**Comment by Striver08** [comment] 2021-03-25 06:17
@bhav09 The issue isn't closed yet, I would like to go for it, Do assign it to me.

**Comment by bhav09** [comment] 2021-03-25 06:27
Hey @Striver08 the issue isn't closed yet but it already has been assigned to someone.

**Closed as completed** 2021-03-29 11:53 UTC
Labels: Python, gssoc21

**Comment by OnewayShruti** [comment] 2021-03-29 12:26
Hi I have made a pr for the same today.But without being this issue was
closed.
I am confused whether my solution was regected or time has exceeded?
Please guide me.
