### ISSUE TITLE
[GSSOC'21] Adding solutions of Important Backtracking Problems

### ISSUE THREAD

**Issue by SanskaarPatni** [HarshCasper/NeoAlgo#2497] opened 2021-03-10 06:33 UTC
I would love to add solutions of backtracking problems in JAVA.
@iamrajiv can you assign me the issue as a part of gssoc'21?

**Comment by AasthaGoyalgit** [comment] 2021-03-10 07:51
Hi,
I would like to work on this issue in java. Could you please assign it to me?

Thanks!!

**Comment by priyanka001tech** [comment] 2021-03-10 14:17
Hello,
I would like to work on it.

**Comment by drishika2002** [comment] 2021-03-11 06:39
Hello, I would like to work on this issue in C++.
Can you please assign it to me as a part of GSSOC'21?

**Comment by neha07kumari** [comment] 2021-03-11 17:31
### Feature
Solutions of important backtracking problems
### Language: C++

### Have you read the Contributing Guidelines on Pull Requests?
Yes

### Motivation
I want to contribute to it under GSSoC'21.

### Pitch
It is a good application for data structure. I would like to take up this task to implement it in C++. @bhav09

**Comment by bhav09** [comment] 2021-03-11 17:59
@neha07kumari can you please enlist a few problem statements?

**Comment by kanchan1910** [comment] 2021-03-11 18:09
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

some of the problems are :suduko, N queen problem, permutations, subsets, combinational sum, generate all parenthesis

**Comment by bhav09** [comment] 2021-03-12 06:26
Whatever problem statements you would want to work on open an issue and enlist the problem neatly with all the details. The mentoring team will review it and if seems legit the issue will be assigned. Hope this helps. 
Happy Learning!

**Comment by kanchan1910** [comment] 2021-03-12 07:07
Hey @bhav09, I am Kanchan Jeswani, a GSSOC'21 participant I want to add the code for the problem "Generate all valid parentheses".

The problem statement is as follows:

Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses of length 2*n.

For example, given n = 3, a solution set is:
[
  "((()))",
  "(()())",
  "(())()",
  "()(())",
  "()()()"
]
for n = 1
[
"()"
]
 for n = 2
[
"(())",
"()()"
]

The input of the form: an integer n 
Output: the vector of all possible combinations of well-formed parentheses of length 2*n in the form of a vector of strings like shown in the above examples.

n =3 means, there are 3 open parentheses and 3 close parentheses, and we have to form all well-formed possible combinations using these parentheses.

constraint : 1 <= n <= 8

I would love to solve this problem using CPP with well-explained code.
Please assign me this.
Hope to hear from you.
Discord username kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by bhav09** [comment] 2021-03-12 07:23
@kanchan1910, great one! You can open an issue and tag me in it. I will check and assign it to you.

**Comment by kanchan1910** [comment] 2021-03-12 07:35
@bhav09 Done sir! thank you

**Comment by kanchan1910** [comment] 2021-03-12 15:52
Hello @bhav09, I have now opened the issue and tagged you there, kindly check it and if it seems to be fine please assign me.
The link for the same is: https://github.com/Algo-Phantoms/Algo-Tree/issues/732#issue-829841555 
Thank you!

**Comment by bhav09** [comment] 2021-03-13 01:08
@kanchan1910, you have opened the issue at some other repo. I would be able to assign you only when the issue is under Tesseract Coding.

**Comment by kanchan1910** [comment] 2021-03-13 01:31
@bhav09, apologies for my mistake, now I have done it. Kindly check this.
Thank you

**Comment by bhav09** [comment] 2021-03-13 01:33
Done @kanchan1910 :)

**Closed as completed** 2021-03-13 03:41 UTC
Labels: gssoc21
