### ISSUE TITLE
Knapsack Problem

### ISSUE THREAD

**Issue by Preetesh21** [HarshCasper/NeoAlgo#1093] opened 2020-09-26 06:43 UTC
## 💥 Proposal

Program for the DP problem Knapsack

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes.

I would like to contribute in C and C++ language.

**Comment by ritvij14** [comment] 2020-09-26 10:09
Possible duplicate of #423

**Closed as completed** 2020-09-26 10:13 UTC
Labels: C
